spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: springboot
    password: springboot
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    
kafka:
  topic:
    user-random-topic: user-random-topic

server:
  port: 9050

